# This script will create an excel file from the two annotation files generated by ANNOVAR.
#
# Roslen Anacleto
# 20160305
#

suppressMessages(library(dplyr))

args<-base::commandArgs(trailingOnly=T)

# Note: **basename** and **dirname** are useful in extracting the traitname and fullpath from the
# commandline parameter. However, since the requirement is to specify only the trait name and
# since the filesystem is organized such that all trait names are individual subdirectory names
# on the same level as this script, then there is no need to extract the basename and dirname.

if (length(args) != 1) {
   cat("Usage: Rscript consolidate_annotation_files.R <trait>\n")
   quit(save="no", status=1, runLast=T) # non-zero status means an error has occurred.
} else if (!dir.exists(args[1])) {
   cat(paste0("ERROR: '",args[1],"' does not exist.\n"))
   quit(save="no", status=2, runLast=T)
}


# Load the trait and path from the command line paramter
trait=args[1]
path=trait


variant_filename <- list.files(trait, pattern="\\.variant_function$")
exonic_filename <- list.files(trait, pattern="\\.exonic_variant_function$")

#cat(paste0(variant_filename,"\n"))
#cat(paste0(exonic_filename,"\n"))

cat("Loading functional annotations of significant SNPs...")
var <- read.table(paste0(path,"/",variant_filename), header=F, sep="\t", stringsAsFactors=F)
exn <- read.table(paste0(path,"/",exonic_filename), header=F, sep="\t", stringsAsFactors=F)
cat("DONE.\n")

cat("Consolidating annotations...")
res <- dplyr::left_join(var,exn,by=c("V3"="V4", "V4"="V5", "V5"="V6", "V6"="V7", "V7"="V8"))
write.table(res, file=paste0(path,"/",variant_filename,".consolidated"), append=F, quote=F,
            sep="\t", row.names=F, col.names=F)
cat("DONE.\n")
